# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
#   Overridden in data/themes/
theme = "binarymist"
# Enable users to switch between day and night mode?
day_night = true

# Font style.
#   Choose from `default`, `classic`, or `playfair`.
font = ""
# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "L"
############################
## Basic Info
############################

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type = "LocalBusiness"

# Local business type (optional)
# If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
local_business_type = ""

# Organization name (optional)
# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name = "BinaryMist Ltd"
# Description for social sharing and search engines. If undefined, superuser role is used in place.
description = "Creating Developer First Security"

############################
## Site Features
############################

# Enable global source code highlighting? true/false
# Documentation: https://sourcethemes.com/academic/docs/writing-markdown-latex/#highlighting-options
highlight = true
# highlight_languages = ["r"]  # Add support for highlighting additional languages
# highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
highlight_style = "monokai-sublime"
# highlight_style = "darcula"
# highlight_style = "darkula"

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = false

# Enable diagram rendering? true/false
#   If false, you can enable diagrams on a per page basis as needed.
diagram = false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Enable visitors to edit pages?
#   `repo` defines the repository URL. `editable` defines which page types can be edited.
edit_page = {repo_url = "https://github.com/binarymist/BinaryMistBlog", repo_branch = "master", editable = {docs = false, page = false, post = false}}

show_related = {page = false, post = true, project = false, publication = false, talk = false}

############################
## Contact details
##
## These details power the Contact widget (if enabled).
## Additionally, for organizations, these details may be used to enrich search engine results.
############################

# Enter contact details (optional). To hide a field, clear it to "".
email = "Services@binarymist.net"
phone = "(+64) 274 622 607"

# Address
# For country_code, use the 2-letter ISO code (see https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 )
address = {city = "Christchurch, New Zealand"}

# Geographic coordinates
# To get your coordinates, right-click on Google Maps and choose "What's here?". The coords will show up at the bottom.
# coordinates = {latitude = "37.4275", longitude = "-122.1697"}

# Directions for visitors to locate you.
# directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"

# Office hours
# A list of your office hours. To remove, set to an empty list `[]`.
# office_hours = ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]
office_hours = "24/7 for paying customers"

# Enter an optional link for booking appointments (e.g. calendly.com).
# appointment_url = "https://calendly.com"

# Contact links
#   Set to `[]` to disable, or comment out unwanted lines with a hash `#`.
contact_links = [
  {icon = "twitter", icon_pack = "fab", name = "DM Us", link = "https://twitter.com/binarymist"},
  {icon = "skype", icon_pack = "fab", name = "Skype Us", link = "skype:binarymist?call"},
  # {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  # {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@binarymist"},
  ]

############################
## Social
############################

# Twitter username (without @). Used when a vistor shares your site on Twitter.
twitter = "binarymist"

############################
## Regional Settings
############################

# Date and time format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
#   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "Jan 2, 2006"
#   Examples: "3:04 pm" or "15:04"
time_format = "15:04 PM"

# Address format (choose from the [address_formats] list below or add you own to the list).
address_format = "en-gb"

############################
## Advanced
############################

# Get user avatars from Gravatar.com? (true/false)
gravatar = false

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "r", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display comment count if comments exist, irrelevant of whether commenting is turned on or off.
comment_count = true
# Dissable the submission of new comments, existing comments will remain displayed.
disable_comments = false

# Display next/previous section pager? (true/false)
section_pager = false
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
abstract_length = 135

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
plugins_js  = ["staticmanFormSubmissionValidation"]

# Avatars.
# An avatar is an image that appears next to a user's name.
# An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
[avatar]
  # Get user avatars from Gravatar.com? (true/false)
  gravatar = false

  # Choose a shape for avatar images. Options: circle, square.
  shape = "circle"

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  zh = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}

# Configuration of publication pages.
[publications]
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "January 2006"

  # Citation style ("apa" or "mla")
  citation_style = "apa"

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 3
  talk_view = 2

############################
## Comments
############################
[comments]
  # Comment provider:
  #   "": Disabled
  #   "disqus": (https://disqus.com)
  #   "commento" (https://commento.io)
  provider = ""

  # Which page types are commentable?
  commentable = {page = false, post = true, docs = false, project = false, publication = false, talk = false}

############################
## Search
############################
[search]
  # Search provider:
  #   "": No search engine
  #   "wowchemy": Built-in search engine
  #   "algolia": Algolia (https://www.algolia.com)
  provider = "wowchemy"

  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  [search.algolia]
    min_length = 1  # Only the matches whose length exceeds this value will be returned.
    threshold = 0.3  # Where 0 requires a perfect match and 1 matches anything.

[staticman]
  endpoint = "https://bmstaticmaninstance.herokuapp.com/v3/entry"
  git_provider = 'github'
  git_provider_username = "binarymist"
  repo = "BinaryMistBlog"
  branch = "master"

############################
## Maps
############################
[map]
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   "" No map
  #   "google": Google Maps
  #   "mapnik": OpenStreetMap (Mapnik)
  #   "mapbox": OpenStreetMap (Mapbox)
  provider = ""
  api_key = ""
  zoom = 15

############################
## Marketing
############################
[marketing]
  google_analytics = "UA-106756952-5"
  google_tag_manager = "GTM-MSX3HL3"

############################
## Content Management System
############################
[cms]
  branch = "master"
